server:
  port: 8080
  servlet:
    context-path: /secKill
spring:
  application:
    name: mall-secKill
  datasource:
    url: jdbc:mysql://localhost:3306/lyc_mall?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.40.128
    port: 6379
    password: Lyc123456.
    timeout: 60000
  rabbitmq:
    host: 192.168.40.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.40.128:8848
mybatis-plus:
  #  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:/mapping/**/*.xml
  # 实体类别名包（用于简化 XML 中的类型引用）
  type-aliases-package: com.lyc.learn.entity
  configuration:
    # 开启 SQL 日志打印（开发阶段建议开启）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名映射（数据库 user_name → 实体 userName）
    map-underscore-to-camel-case: true
